apiVersion: v1
kind: Template
metadata:
  name: selectorsyncset-template

parameters:
  - name: REGISTRY_IMG
    required: true
  - name: PACKAGE_IMG
    required: true
  - name: IMAGE_TAG
    required: true
  - name: IMAGE_DIGEST
    required: true
  - name: REPO_NAME
    value: package-operator
    required: true
  - name: DISPLAY_NAME
    value: Package Operator
    required: true

objects:
  - apiVersion: hive.openshift.io/v1
    kind: SelectorSyncSet
    metadata:
      annotations:
        component-display-name: ${DISPLAY_NAME}
        component-name: ${REPO_NAME}
      labels:
        managed.openshift.io/osd: "true"
      name: package-operator
    spec:
      clusterDeploymentSelector:
        matchLabels:
          ext-hypershift.openshift.io/cluster-type: nonexistantlabel
      resourceApplyMode: Sync
      resources:
        - apiVersion: v1
          kind: Namespace
          metadata:
            name: openshift-package-operator
            labels:
              openshift.io/cluster-monitoring: "true"
              package-operator.run/cache: "True"
        - apiVersion: v1
          kind: ServiceAccount
          metadata:
            name: package-operator
            namespace: openshift-package-operator
            labels:
              package-operator.run/cache: "True"
        - apiVersion: rbac.authorization.k8s.io/v1
          kind: ClusterRoleBinding
          metadata:
            name: package-operator
            labels:
              package-operator.run/cache: "True"
          roleRef:
            apiGroup: rbac.authorization.k8s.io
            kind: ClusterRole
            name: cluster-admin
          subjects:
            - kind: ServiceAccount
              name: package-operator
              namespace: openshift-package-operator
        - apiVersion: batch/v1
          kind: Job
          metadata:
            name: package-operator-bootstrap
            namespace: openshift-package-operator
          spec:
            # delete right after completion
            ttlSecondsAfterFinished: 0
            # set deadline to 30min
            activeDeadlineSeconds: 1800
            template:
              spec:
                restartPolicy: OnFailure
                serviceAccountName: package-operator
                initContainers:
                  - name: prepare
                    image: ${REGISTRY_IMG}:${IMAGE_TAG}
                    args: ["-copy-to=/bootstrap-bin/pko"]
                    volumeMounts:
                      - name: shared-dir
                        mountPath: /bootstrap-bin
                containers:
                  - name: package-operator
                    image: ${PACKAGE_IMG}:${IMAGE_TAG}
                    command: ["/.bootstrap-bin/pko",  "-self-bootstrap=${PACKAGE_IMG}:${IMAGE_TAG}"]
                    env:
                      - name: PKO_NAMESPACE
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.namespace
                      - name: PKO_IMAGE
                        value: "${REGISTRY_IMG}:${IMAGE_TAG}"
                    volumeMounts:
                      - name: shared-dir
                        mountPath: /.bootstrap-bin
                volumes:
                  - name: "shared-dir"
                    emptyDir: {}
            backoffLimit: 20
