version: 2
updates:
- package-ecosystem: gomod
  directory: /
  schedule:
    interval: daily
  allow:
  - dependency-type: all
    dependency-name: "*"
  assignees: [ eqrx ]
  reviewers: [ eqrx ]
- package-ecosystem: gomod
  directory: /apis
  schedule:
    interval: daily
  allow:
  - dependency-type: all
    dependency-name: "*"
  assignees: [ eqrx ]
  reviewers: [ eqrx ]
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: daily
