apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    package-operator.run/phase: deploy
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: remote-phase-operator
  name: remote-phase-manager
  namespace: package-operator-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: remote-phase-operator
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: remote-phase-operator
    spec:
      containers:
      - args:
        - --enable-leader-election
        - -target-cluster-kubeconfig-file=/data/kubeconfig
        - -class=hosted-cluster
        env:
        - name: PKO_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: quay.io/package-operator/package-operator-manager:v1.1.0-4-g14485c4
        name: manager
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: kubeconfig
          readOnly: true
      serviceAccountName: remote-phase-operator
      volumes:
      - name: kubeconfig
        secret:
          optional: false
          secretName: admin-kubeconfig
status: {}
