apiVersion: v1
kind: Namespace
metadata:
  name: package-operator-system
  labels:
    package-operator.run/cache: "True"
---
apiVersion: v1
kind: Service
metadata:
  name: package-operator-metrics
  namespace: package-operator-system
  labels:
    app.kubernetes.io/name: package-operator
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: metrics
      port: 8080
      targetPort: metrics
  selector:
    app.kubernetes.io/name: package-operator
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: package-operator
  namespace: package-operator-system
  labels:
    app.kubernetes.io/name: package-operator
    release: prometheus
spec:
  endpoints:
  - interval: 10s
    port: metrics
  selector:
    matchLabels:
      app.kubernetes.io/name: package-operator
