name: Release

on:
  push:
    tags:
    - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: '>=1.20.0'

    - name: Delete non-semver tags
      run: 'git tag -d $(git tag -l | grep -v "^v")'

    - uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Build & Push images
      run: ./mage build:pushImages
      env:
        USE_DIGESTS: "true"
        VERSION: ${{github.ref_name}}
        QUAY_USER: ${{ secrets.QUAY_USER }}
        QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}

    - uses: cytopia/upload-artifact-retry-action@v0.1.7
      if: ${{ always() }}
      with:
        name: bootstrap-job
        path: |
          config/self-bootstrap-job.yaml

    - name: Build release binaries
      run: ./mage build:releaseBinaries

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          config/self-bootstrap-job.yaml
          bin/kubectl-package_darwin_amd64
          bin/kubectl-package_darwin_arm64
          bin/kubectl-package_linux_amd64

    - name: Create git tag for apis/ submodule
      run: |
        export GIT_AUTHOR_NAME="$(git show --format=%an -s $GITHUB_REF_NAME | tail -1)"
        export GIT_AUTHOR_EMAIL="$(git show --format=%ae -s $GITHUB_REF_NAME | tail -1)"
        git tag -a apis/$GITHUB_REF_NAME -m apis/$GITHUB_REF_NAME $GITHUB_REF_NAME
        git push origin apis/$GITHUB_REF_NAME
