name: Update project dependencies
on:
  workflow_dispatch: ~
permissions:
  pull-requests: write
jobs:
  go:
    if: github.repository_owner == 'package-operator'
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: '>=1.20.0'
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cache/package-operator
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - run: |
        go get -u ./...
        go mod tidy
      working-directory: .
    - run: |
        go get -u ./...
        go mod tidy
      working-directory: ./apis
    - uses: peter-evans/create-pull-request@v4
      with:
        title: Update go dependencies
        commit-message: Update go dependencies
        body: Update go dependencies
        labels: ok-to-test, tide/merge-method-squash
        branch: deps
        delete-branch: true
        assignees: eqrx
        reviewers: eqrx
